import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#717977",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#c3eae6",
        "background": "#f9f9f8",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c0c8c6",
        "secondary-container": "#e7d6fe",
        "on-primary": "#ffffff",
        "primary-container": "#bae1dd",
        "secondary-fixed": "#ecdcff",
        "inverse-primary": "#a7ceca",
        "tertiary-fixed": "#fcdcd0",
        "secondary-fixed-dim": "#d0c0e7",
        "surface-container-high": "#e8e8e7",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f1f1f0",
        "on-primary-container": "#416562",
        "surface-bright": "#f9f9f8",
        "tertiary-container": "#f2d3c7",
        "error-container": "#ffdad6",
        "secondary": "#65587a",
        "on-tertiary-fixed-variant": "#574239",
        "on-error": "#ffffff",
        "surface-variant": "#e2e2e1",
        "on-background": "#1a1c1c",
        "on-secondary-container": "#685b7d",
        "on-primary-fixed": "#00201e",
        "inverse-surface": "#2f3130",
        "on-surface": "#1a1c1c",
        "surface": "#f9f9f8",
        "on-surface-variant": "#414847",
        "tertiary-fixed-dim": "#dec0b5",
        "on-secondary-fixed": "#211633",
        "surface-container-highest": "#e2e2e1",
        "tertiary": "#715950",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#a7ceca",
        "on-tertiary-container": "#715a50",
        "primary": "#416562",
        "on-tertiary-fixed": "#281811",
        "surface-tint": "#416562",
        "on-secondary-fixed-variant": "#4d4161",
        "error": "#ba1a1a",
        "surface-container": "#eeeeed",
        "surface-dim": "#dadad9",
        "surface-container-low": "#f4f4f2",
        "on-primary-fixed-variant": "#284d4a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "24px",
        lg: "40px",
        xs: "4px",
        sm: "12px",
        xl: "64px",
        margin: "32px",
        gutter: "24px",
        base: "8px",
      },
      fontFamily: {
        sans: ["Lexend", "sans-serif"],
        lexend: ["Lexend", "sans-serif"],
      },
      fontSize: {
        h1: ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        display: ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        h3: ["20px", { lineHeight: "1.5", fontWeight: "500" }],
        h2: ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "1", fontWeight: "500" }],
      },
      boxShadow: {
        "pastel-primary": "0 8px 24px -4px rgba(65, 101, 98, 0.1)",
        "pastel-secondary": "0 8px 24px -4px rgba(101, 88, 122, 0.1)",
      },
    },
  },
  plugins: [],
};
export default config;
